### ISSUE TITLE
support single slash for one letter options

### ISSUE THREAD

**Issue by charlierudolph** [sindresorhus/dargs#16]
Most one letter options use a single slash.

```javascript
dargs({a: 'b'}, {shortOpts: true}) // returns ["-a=b"]
```

**Comment by kevva** [comment]
This sounds fragile and, since most *good* command line apps support long flags, unnecessary.

**Comment by charlierudolph** [comment]
Why is this fragile? And can you give an example of a CLI that uses two dashes with a one letter option. I've personally never seen one.

I do agree you should probably just use long flags but I don't see the harm here. 

Looking at minimist's parsing it does appear the short options should not use equal signs 
```
> minimist(["-a=1"])
{ _: [], a: '=1' }

> minimist(["-a","1"])
{ _: [], a: 1 }
```

**Comment by kevva** [comment]
> Why is this fragile? And can you give an example of a CLI that uses two dashes with a one letter option. I've personally never seen one.

Nah, that's probably true. So maybe not that fragile.

**Comment by sindresorhus** [comment]
Better question, why would you ever do `dargs({a: 'b'});`. What's your use-case?

**Comment by charlierudolph** [comment]
My use case was simply trying to use single character options and it not doing what I expected. I agree the long options are better for code readability. If you think its not a valid use case how do you feel about throwing in a warning when a single character option is used? And add some documentation that short options are not supported?

**Comment by charlierudolph** [comment]
@kevva @sindresorhus any thoughts?

**Comment by sindresorhus** [comment]
I guess we can be nice and support this as some Unix tools actually only support short option, but we should be very clear about preferring long options. A good PR with tests would be welcomed ;)

**Comment by radkodinev** [comment]
IMO short options are good to have.
I had a related PR closed a long time ago so if you guys need some ideas take a look at #4.
