### ISSUE TITLE
support space instead of equals

### ISSUE THREAD

**Issue by charlierudolph** [sindresorhus/dargs#17]
Would be nice if there was an option to use spaces instead of equals.

```javascript
dargs({abc: 'def'}, {equals: false}) // returns ["--abc", "def"]
```

**Comment by kevva** [comment]
Why?

**Comment by sindresorhus** [comment]
@charlierudolph Happy to entertain this if you have some good use-cases.

**Comment by charlierudolph** [comment]
I think the only real use case is a built in need for the #16
