### ISSUE TITLE
append _ args to end, by default

### ISSUE THREAD

**Issue by chrisirhc** [sindresorhus/dargs#19]
I'm not sure if this is desirable behavior, but right now:

```
> dargs({'_': ['a', 'b']})
[ '--_=a', '--_=b' ]
>
```

Should it instead return the arguments without prepending the odd `--_=`?
Just request for comment before making a PR if people agree on the right behavior.
This also makes the behavior more symmetric with minimist.

**Comment by sindresorhus** [comment]
I've never needed it, but sure if you do a PR.

**Comment by mshenfield** [comment]
Updated @chrisirhc 's diff to fix merge conflicts. Added documentation, updated diff to use main ex/inclusion and alias logic, handle a value or Array passed to "_", and treat all values in "_" Array as a String.

**Comment by chrisirhc** [comment]
Thank you @mshenfield !

**Comment by mshenfield** [comment]
Sure!
