### ISSUE TITLE
Add option to disable `=` in flags

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/dargs#25]
Some crappy arguments parsers like the one Compass and Sass uses doesn't support `--foo=bar` type flags and instead require `--foo bar`.

What should the option be named? Help wanted.

**Comment by radkodinev** [comment]
It has to do with long options and the equals sign so something like `useLongOptionEqualsSign` or `longOptionEquals` (with default `true`)?

**Comment by sindresorhus** [comment]
You can use `=` with short flags too. At least with [`minimist`](https://github.com/substack/minimist/commit/6bbe14529166245e86424f220a2321442fe88dc3).

**Comment by radkodinev** [comment]
... which isn't the standard situation in the *nix world but so isn't the case with Compass and Sass you have referred to.

Then perhaps something as short and simple as `useEquals` / `useEqualsDelimiter`?

**Comment by sindresorhus** [comment]
Yeah, something like that sounds better.

**Comment by sindresorhus** [comment]
@mshenfield Interested? No worries if not :)

**Comment by mshenfield** [comment]
Sure! The pull request I submitted lets the user set the separator to any value (e.g. 'foo bar', 'foo--bar'). Let me know if that is too broad, I have another branch that [implements the `useEquals` option](https://github.com/mshenfield/dargs/tree/issue-25-add-option-use-equals) per the original request.
