### ISSUE TITLE
No single flag support? 

### ISSUE THREAD

**Issue by reggi** [sindresorhus/dargs#32]
I see there's alias support, but this behavior below is kind of unexpected. Would love to know what others think here. Shouldn't `minimist` and `dargs` be inter-operable? 

```js
console.log(process.argv.slice(2))
console.log(minimist(process.argv.slice(2)))
console.log(dargs(minimist(process.argv.slice(2))))
console.log(minimist(dargs(minimist(process.argv.slice(2)))))
```

```js
[ 'list', '--animal', 'meow', '-A', '-L', '-P', '-H', '-A' ]
{ _: [ 'list' ],
  animal: 'meow',
  A: true,
  L: true,
  P: true,
  H: true }
[ '--animal=meow', '---a', '---l', '---p', '---h', 'list' ]
{ _: [],
  animal: 'meow',
  '-a': true,
  '-l': true,
  '-p': true,
  '-h': 'list' }
```

**Comment by sindresorhus** [comment]
Do you have an actual need for this? Explain your use-case. There's no direct single-flag support as it has never been requested and I personally don't see the use-case. When would you ever want to support doing `{a: true}` in your API?

**Comment by reggi** [comment]
Hey @sindresorhus, thanks for the quick reply. 

I'm proxying some bash commands and I need to parse using `minimist` and then pass the parent commands along to a child process again. 

There are a couple of other options I found that follow `minimist`. Feel free to close.

* https://github.com/asbjornenge/minimist-reverse
* https://www.npmjs.com/package/maximist
* https://www.npmjs.com/package/tsiminim

**Comment by sindresorhus** [comment]
Alright. I would accept a PR if you want this here, but probably easier to use any of those packages.

**Comment by tunnckoCore** [comment]
@sindresorhus any reconsideration about that? It's definitely [a one line change](https://github.com/tunnckoCore/dargs-fork/blob/master/index.js#L25-L29)

**Comment by sindresorhus** [comment]
@tunnckoCore I already accepted it if anyone wants to do a PR with docs and tests.

**Comment by tunnckoCore** [comment]
Oooh, yea, miss-looked you last comment :) I'll PR then.

**Comment by tunnckoCore** [comment]
@sindresorhus, probably behind some option? Because most of the tests are failing. Which is normal - e.g. `{ a: 123 }` now becomes `['-a=123']`.
