### ISSUE TITLE
camelCase option

### ISSUE THREAD

**Issue by jaridmargolin** [sindresorhus/dargs#33]
Are you open to exposing an option `camelCase` (or something similar) which would bypass the `replace` and `toLowerCase` code found here: https://github.com/sindresorhus/dargs/blob/master/index.js#L14 ?

I'd be happy to submit a PR...

**Comment by sindresorhus** [comment]
Why? For what use-case?

**Comment by jaridmargolin** [comment]
My particular use case involves building a tool which is intended to work in conjunction with a config file, where dot notation is used to set nested values. Ex:

```
--selenium.browserVersion=latest
// sets/overwrites selenium: { browserVersion: 'latest' }
```

Currently dargs is converting this to `--selenium.browser-version`... Although yargs does utilize `camel-case-expansion` by default, it does not appear to expand arguments using dot notation. And even if this was fixed within yargs (I will file an issue), I'm not a huge fan of the config holding both the expanded and non expanded values.

It is absolutely possible for me to take another pass on the object returned by dargs and reformat to utilize camelCase args, but I believe the solution would be significantly simplified if dargs exposed an option.

**Comment by sindresorhus** [comment]
Sure, valid use-case. Pull request welcome :)

**Comment by jaridmargolin** [comment]
Thanks for the help getting this out the door!

**Comment by kevva** [comment]
:+1:
