### ISSUE TITLE
CamelCase should combine

### ISSUE THREAD

**Issue by atian25** [sindresorhus/dargs#35]
- `yargs` will parse `--debug-brk` as ` { 'debug-brk': true, 'debugBrk': true}`
- `dargs({ 'debug-brk': true, 'debugBrk': true})` should provide an options to only output one.

workaround: `[ ...new Set(dargs(input) ]`

**Comment by sindresorhus** [comment]
Valid request, but I think this should be solved in `yargs`. It shouldn't output both formats, or should at least have an option to turn that off. Open an issue on `yargs`.
