### ISSUE TITLE
feature request: custom pushArg or handler hook

### ISSUE THREAD

**Issue by atian25** [sindresorhus/dargs#36]
```js
const input = { debug: 7000, baseDir: 'dist' };
const output = dargs(input, {
  excludes: [ /^debug.*/],
  handler(key) {
    // so we can handler when match
    delete input[key];
  }
});

// got: input : { baseDir: 'dist' } , output: [ '--debug=7000']
``

**Comment by mshenfield** [comment]
Would this hook be called when a key matches one of the `excludes`, or if the key is about to be parsed and added to the output array?

**Comment by atian25** [comment]
currently, only need to call once after `pushArg`

**Comment by sindresorhus** [comment]
You can easily handle this yourself before passing it to `dargs`. I don't see the need to bloat `dargs` with this kind of functionality.

**Comment by atian25** [comment]
that means I should find the keys by `exclude` / `include` myself.

anyway, I'd handler this myself.
