### ISSUE TITLE
Package is not available as commonjs module

### ISSUE THREAD

**Issue by shsuman** [sindresorhus/dargs#44]
I am trying to use this module in Node.js environment and it seems like it only ships in ESM format, however I need a commonjs format.

**Comment by sindresorhus** [comment]
Node.js supports ESM.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by shsuman** [comment]
Will you be willing to accept PRs to make this package Hybrid(Both ESM and CommonJS). I am working in an electron environment and that doesn't support ESM.
