### ISSUE TITLE
Wrap values in quotes

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/dargs#46]
```
dargs({path: '/a path with spaces.txt'})
```

`path` needs to be wrapped in quotes.

---

## Workaround

```js
  function quoteAllStrings(obj) {
    for (const key of Object.keys(obj)) {
      const val = obj[key]
      if (typeof val === 'string' || val instanceof String)
        obj[key] = `"${obj[key]}"`
    }
  }
```

**Comment by sindresorhus** [comment]
Command-line arguments *can* have spaces. I think you're thinking of a shell command, which does indeed need to be escaped. That's outside the scope of this package.
